use phf::phf_map;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenType {
    Nonsense,
    IntegerBig,
    Integer64,
    Integer32,
    Integer16,
    Integer8,
    UInteger64,
    UInteger32,
    UInteger16,
    UInteger8,
    String,
    None,
    Colon,
    Dot,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Plus,
    Minus,
    Asterisk,
    Slash,
    Assign,
    Eq,
    NotEq,
    Bang,
    BoolNot,
    Var,
    Lt,
    Gt,
    Semicolon,
    Eol,
    Ident,
    Illegal,
    BoolTrue,
    BoolFalse,
    Return,
    LParen,
    RParen,
    If,
    BoolAnd,
    BoolOr,
    Then,
    Elseif,
    Else,
    Func,
    Comma,
    Class,
    Struct,
    Public,
    Private,
    Readonly,
    For,
    In,
    While,
    New,
    Import,
    From,
    Let,
    GetClassMember,
    Comment,
    TestPrint,
    Use,
    NumberSign, // #
    Break,
    Continue,
    Eof,
}

impl TokenType {
    /// 获取 TokenType 的字符串表示
    pub fn to_string(&self) -> &'static str {
        match self {
            TokenType::Struct => "Struct",
            TokenType::Colon => ":",
            TokenType::Dot => ".",
            TokenType::LBracket => "[",
            TokenType::RBracket => "]",
            TokenType::LBrace => "{",
            TokenType::RBrace => "}",
            TokenType::Plus => "+",
            TokenType::Minus => "-",
            TokenType::Asterisk => "*",
            TokenType::Slash => "/",
            TokenType::Assign => "=",
            TokenType::Eq => "==",
            TokenType::NotEq => "!=",
            TokenType::Bang => "!",
            TokenType::BoolNot => "Not",
            TokenType::Lt => "<",
            TokenType::Var => "Var",
            TokenType::Gt => ">",
            TokenType::Semicolon => ";",
            TokenType::Eol => "New Line",
            TokenType::BoolTrue => "True",
            TokenType::BoolFalse => "False",
            TokenType::Return => "Return",
            TokenType::LParen => "(",
            TokenType::RParen => ")",
            TokenType::If => "If",
            TokenType::BoolAnd => "And",
            TokenType::BoolOr => "Or",
            TokenType::Then => "Then",
            TokenType::Elseif => "ElseIf",
            TokenType::Else => "Else",
            TokenType::Func => "Func",
            TokenType::Comma => ",",
            TokenType::Class => "Class",
            TokenType::Public => "PUBLIC",
            TokenType::Private => "PRIVATE",
            TokenType::Readonly => "READONLY",
            TokenType::For => "For",
            TokenType::In => "In",
            TokenType::While => "While",
            TokenType::New => "New",
            TokenType::Import => "Import",
            TokenType::From => "From",
            TokenType::Let => "Let",
            // TokenType::Throw => "Throw",
            TokenType::Eof => "End Of File",
            TokenType::Illegal => "Illegal",
            TokenType::Ident => "Identifier",
            TokenType::Nonsense => "Nonsense",
            TokenType::IntegerBig => "Integer",
            TokenType::Integer64 => "Integer64",
            TokenType::Integer32 => "Integer32",
            TokenType::Integer16 => "Integer16",
            TokenType::Integer8 => "Integer8",
            TokenType::UInteger64 => "UInteger64",
            TokenType::UInteger32 => "UInteger32",
            TokenType::UInteger16 => "UInteger16",
            TokenType::UInteger8 => "UInteger8",      
            TokenType::String => "String",
            TokenType::GetClassMember => "::",
            TokenType::TestPrint => "TestPrint",
            TokenType::Comment => "Comment",
            TokenType::None => "None",
            TokenType::Use => "Use",
            TokenType::NumberSign => "#",
            TokenType::Break => "Break",
            TokenType::Continue => "Continue",
        }
    }
}

pub static TOKEN_TYPE_MAP: phf::Map<&'static str, TokenType> = phf_map! {
    ":" => TokenType::Colon,
    "." => TokenType::Dot,
    "[" => TokenType::LBracket,
    "]" => TokenType::RBracket,
    "{" => TokenType::LBrace,
    "}" => TokenType::RBrace,
    "+" => TokenType::Plus,
    "-" => TokenType::Minus,
    "*" => TokenType::Asterisk,
    "/" => TokenType::Slash,
    "=" => TokenType::Assign,
    "==" => TokenType::Eq,
    "!=" => TokenType::NotEq,
    "<>" => TokenType::NotEq,
    "!" => TokenType::Bang,
    "NOT" => TokenType::BoolNot,
    "VAR" => TokenType::Var,
    "<" => TokenType::Lt,
    ">" => TokenType::Gt,
    ";" => TokenType::Semicolon,
    "\n" => TokenType::Eol,
    "TRUE" => TokenType::BoolTrue,
    "FALSE" => TokenType::BoolFalse,
    "RETURN" => TokenType::Return,
    "(" => TokenType::LParen,
    ")" => TokenType::RParen,
    "IF" => TokenType::If,
    "AND" => TokenType::BoolAnd,
    "OR" => TokenType::BoolOr,
    "THEN" => TokenType::Then,
    "ELSEIF" => TokenType::Elseif,
    "ELSE" => TokenType::Else,
    "FUNC" => TokenType::Func,
    "," => TokenType::Comma,
    "CLASS" => TokenType::Class,
    "PUBLIC" => TokenType::Public,
    "PRIVATE" => TokenType::Private,
    "READONLY" => TokenType::Readonly,
    "FOR" => TokenType::For,
    "IN" => TokenType::In,
    "WHILE" => TokenType::While,
    "NEW" => TokenType::New,
    "IMPORT" => TokenType::Import,
    "STRUCT" => TokenType::Struct,
    "FROM" => TokenType::From,
    "LET" => TokenType::Let,
    "::" => TokenType::GetClassMember,
    "TESTPRINT" => TokenType::TestPrint,
    "NONE" => TokenType::None,
    "USE" => TokenType::Use,
    "#" => TokenType::NumberSign,
    "BREAK" => TokenType::Break,
    "CONTINUE" => TokenType::Continue,
    "\0" => TokenType::Eof,
};

pub enum TokenNumType {
    Int64(String),
    Int32(String),
    Int16(String),
    Int8(String),
    UInt64(String),
    UInt32(String),
    UInt16(String),
    UInt8(String),
    Big(String)
}