use phf::phf_map;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenType {
    Nonsense,
    IntegerBig,
    Integer64,
    Integer32,
    Integer16,
    Integer8,
    UInteger64,
    UInteger32,
    UInteger16,
    UInteger8,
    String,
    None,
    Colon,
    Dot,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Plus,
    Minus,
    Asterisk,
    Slash,
    Assign,
    Eq,
    NotEq,
    Bang,
    BoolNot,
    Var,
    Lt,
    Gt,
    Semicolon,
    Eol,
    Ident,
    Illegal,
    BoolTrue,
    BoolFalse,
    Return,
    LParen,
    RParen,
    If,
    BoolAnd,
    BoolOr,
    Then,
    Else,
    Func,
    Comma,
    Class,
    Struct,
    Public,
    Private,
    Readonly,
    For,
    In,
    While,
    New,
    Import,
    From,
    Let,
    GetClassMember,
    Comment,
    TestPrint,
    Use,
    NumberSign, // #
    Break,
    Continue,
    Extern,
    As,
    Eof,
}

impl TokenType {
    /// 获取 TokenType 的字符串表示
    pub fn to_string(&self) -> &'static str {
        match self {
            TokenType::Struct => "struct",
            TokenType::Extern => "extern",
            TokenType::As => "as",
            TokenType::Colon => ":",
            TokenType::Dot => ".",
            TokenType::LBracket => "[",
            TokenType::RBracket => "]",
            TokenType::LBrace => "{",
            TokenType::RBrace => "}",
            TokenType::Plus => "+",
            TokenType::Minus => "-",
            TokenType::Asterisk => "*",
            TokenType::Slash => "/",
            TokenType::Assign => "=",
            TokenType::Eq => "==",
            TokenType::NotEq => "!=",
            TokenType::Bang => "!",
            TokenType::BoolNot => "not",
            TokenType::Lt => "<",
            TokenType::Var => "var",
            TokenType::Gt => ">",
            TokenType::Semicolon => ";",
            TokenType::Eol => r"\n",
            TokenType::BoolTrue => "true",
            TokenType::BoolFalse => "false",
            TokenType::Return => "return",
            TokenType::LParen => "(",
            TokenType::RParen => ")",
            TokenType::If => "if",
            TokenType::BoolAnd => "and",
            TokenType::BoolOr => "or",
            TokenType::Then => "then",
            TokenType::Else => "else",
            TokenType::Func => "func",
            TokenType::Comma => ",",
            TokenType::Class => "class",
            TokenType::Public => "PUBLIC",
            TokenType::Private => "PRIVATE",
            TokenType::Readonly => "READONLY",
            TokenType::For => "for",
            TokenType::In => "in",
            TokenType::While => "while",
            TokenType::New => "new",
            TokenType::Import => "import",
            TokenType::From => "from",
            TokenType::Let => "let",
            // TokenType::Throw => "Throw",
            TokenType::Eof => "end of file",
            TokenType::Illegal => "illegal",
            TokenType::Ident => "identifier",
            TokenType::Nonsense => "nonsense",
            TokenType::IntegerBig => "integer",
            TokenType::Integer64 => "integer64",
            TokenType::Integer32 => "integer32",
            TokenType::Integer16 => "integer16",
            TokenType::Integer8 => "integer8",
            TokenType::UInteger64 => "uinteger64",
            TokenType::UInteger32 => "uinteger32",
            TokenType::UInteger16 => "uinteger16",
            TokenType::UInteger8 => "uinteger8",      
            TokenType::String => "string",
            TokenType::GetClassMember => "::",
            TokenType::TestPrint => "testprint",
            TokenType::Comment => "comment",
            TokenType::None => "None",
            TokenType::Use => "use",
            TokenType::NumberSign => "#",
            TokenType::Break => "break",
            TokenType::Continue => "continue",
        }
    }
}

pub static TOKEN_TYPE_MAP: phf::Map<&'static str, TokenType> = phf_map! {
    ":" => TokenType::Colon,
    "." => TokenType::Dot,
    "[" => TokenType::LBracket,
    "]" => TokenType::RBracket,
    "{" => TokenType::LBrace,
    "}" => TokenType::RBrace,
    "+" => TokenType::Plus,
    "-" => TokenType::Minus,
    "*" => TokenType::Asterisk,
    "/" => TokenType::Slash,
    "=" => TokenType::Assign,
    "==" => TokenType::Eq,
    "!=" => TokenType::NotEq,
    "<>" => TokenType::NotEq,
    "!" => TokenType::Bang,
    "NOT" => TokenType::BoolNot,
    "VAR" => TokenType::Var,
    "<" => TokenType::Lt,
    ">" => TokenType::Gt,
    ";" => TokenType::Semicolon,
    "\n" => TokenType::Eol,
    "TRUE" => TokenType::BoolTrue,
    "FALSE" => TokenType::BoolFalse,
    "RETURN" => TokenType::Return,
    "(" => TokenType::LParen,
    ")" => TokenType::RParen,
    "IF" => TokenType::If,
    "AS" => TokenType::As,
    "AND" => TokenType::BoolAnd,
    "OR" => TokenType::BoolOr,
    "THEN" => TokenType::Then,
    "ELSE" => TokenType::Else,
    "EXTERN" => TokenType::Extern,
    "FUNC" => TokenType::Func,
    "," => TokenType::Comma,
    "CLASS" => TokenType::Class,
    "PUBLIC" => TokenType::Public,
    "PRIVATE" => TokenType::Private,
    "READONLY" => TokenType::Readonly,
    "FOR" => TokenType::For,
    "IN" => TokenType::In,
    "WHILE" => TokenType::While,
    "NEW" => TokenType::New,
    "IMPORT" => TokenType::Import,
    "STRUCT" => TokenType::Struct,
    "FROM" => TokenType::From,
    "LET" => TokenType::Let,
    "::" => TokenType::GetClassMember,
    "TESTPRINT" => TokenType::TestPrint,
    "NONE" => TokenType::None,
    "USE" => TokenType::Use,
    "#" => TokenType::NumberSign,
    "BREAK" => TokenType::Break,
    "CONTINUE" => TokenType::Continue,
    "\0" => TokenType::Eof,
};

pub enum TokenNumType {
    Int64(String),
    Int32(String),
    Int16(String),
    Int8(String),
    UInt64(String),
    UInt32(String),
    UInt16(String),
    UInt8(String),
    Big(String)
}